### ISSUE TITLE
ChEBI mapping during build process causing inconsistencies in DrOn

### ISSUE THREAD

**Issue by hoganwr** [ufbmi/dron#18]
When the RxNorm conversion process discovers a new ingredient, it mints an DrOn IRI for it, and places it as a subclass of OBI's processed material. This assertion is made in the generated dron-ingredient.owl file.

Then, when the build process replaces DrOn IRIs with mapped ChEBI IRIs, it leaves these subclass of (processed material) assertions in place, thereby asserting that approx 473 ChEBI classes are subclassOf OBI:processed material.

This leads to inconsistencies in the merged dron.owl file.

The following command identifies the offending lines:
grep "SubClassOf.*CHEBI_.*/OBI_0000047" components/dron-ingredient.owl|less

Then you can create a new dron-ingredient.owl file by excluding these lines by adding the -v switch:
grep -v "SubClassOf.*CHEBI_.*/OBI_0000047" components/dron-ingredient.owl > components/dron-ingredient-new.owl

Then you could delete the old dron-ingredient.owl and rename dron-ingredient-new.owl to dron-ingredient.owl

I did all this, tested it, and it works.

The issue is to see if we can add these steps to the ODK build process.

**Comment by matentzn** [comment]
Dron Identifiers are considered "processed material" and CHEBI identifiers are not?

Are both clearly enough separates so that a CHEBI identifier can never be the child of a DRON identifier?

**Comment by hoganwr** [comment]
The issue is the creation of contradictions.  I didn't spend too much time figuring out why certain (but not all) ChEBI IDs as children of OBI's processed material causes them.  But they do.  And I have no problem leaving ChEBI's hierarchy entirely up to ChEBI.

**Comment by matentzn** [comment]
Sounds great!
