### ISSUE TITLE
DRON:00000073 unsatisfiable

### ISSUE THREAD

**Issue by matentzn** [ufbmi/dron#2]
The offending axiom was in dron-upper.owl:

```
SubClassOf(<http://purl.obolibrary.org/obo/DRON_00000073> ObjectIntersectionOf(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000054> <http://purl.obolibrary.org/obo/GO_0008150>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002211> <http://purl.obolibrary.org/obo/GO_0050886>)))
```

I removed this axiom now. The problem is this:
- [hormone therapeutic function](http://purl.obolibrary.org/obo/DRON_00000073) SubClassOf ([realized in](http://purl.obolibrary.org/obo/BFO_0000054) some [biological_process](http://purl.obolibrary.org/obo/GO_0008150)) and ([regulates](http://purl.obolibrary.org/obo/RO_0002211) some [endocrine process](http://purl.obolibrary.org/obo/GO_0050886)) [dron.owl]
- [realized in](http://purl.obolibrary.org/obo/BFO_0000054) Domain [realizable entity](http://purl.obolibrary.org/obo/BFO_0000017) [dron.owl] (realizable entity is a continuant)
- [regulates](http://purl.obolibrary.org/obo/RO_0002211) Domain [process](http://purl.obolibrary.org/obo/BFO_0000015) [dron.owl]  (process is an occurrent)
- contiunants and occurrents are disjoint

This is fixed in Dron now, but should be reviewed and closed by the Dron committee.

**Comment by sjbost** [comment]
@hoganwr will investigate.

**Comment by sjbost** [comment]
@hoganwr will aim to resolve by 12/15
