### ISSUE TITLE
list of additional compounds needing calcium channel blocking disposition

### ISSUE THREAD

**Issue by hoganwr** [ufbmi/DrOn#21]
clevidipine	http://purl.obolibrary.org/obo/DRON_00017480
Isradipine	http://purl.obolibrary.org/obo/DRON_00012645
lacidipine	http://purl.obolibrary.org/obo/DRON_00010944
lercanidipine	http://purl.obolibrary.org/obo/DRON_00013598
manidipine	http://purl.obolibrary.org/obo/DRON_00015228
nilvadipine	http://purl.obolibrary.org/obo/DRON_00015405
Nisoldipine	http://purl.obolibrary.org/obo/DRON_00011196
Nitrendipine	http://purl.obolibrary.org/obo/DRON_00015414
Gallopamil	http://purl.obolibrary.org/obo/DRON_00014987
Fendiline	http://purl.obolibrary.org/obo/DRON_00010752

disposition URI - http://purl.obolibrary.org/obo/DRON_00020325

**Comment by joshhanna** [comment]
Done.
