### ISSUE TITLE
create angiotensin receptor blocker disposition and add to list

### ISSUE THREAD

**Issue by hoganwr** [ufbmi/DrOn#22]
label: function-inhibiting angiotensin receptor binding disposition

add to:
Losartan	http://purl.obolibrary.org/obo/CHEBI_6541
Candesartan	http://purl.obolibrary.org/obo/CHEBI_3347
Valsartan	http://purl.obolibrary.org/obo/DRON_00017695
Irbesartan	http://purl.obolibrary.org/obo/DRON_00010124
Telmisartan	http://purl.obolibrary.org/obo/DRON_00017709
Eprosartan	http://purl.obolibrary.org/obo/DRON_00013631
Olmesartan	http://purl.obolibrary.org/obo/CHEBI_48416
Azilsartan	http://purl.obolibrary.org/obo/DRON_00020174

**Comment by joshhanna** [comment]
Done.
