### ISSUE TITLE
Add CYP2C19 dispositions and assign to relevant molecule types

### ISSUE THREAD

**Issue by joshhanna** [ufbmi/DrOn#4]
_From @GoogleCodeExporter on March 17, 2015 14:47_

```
Subproject for new version of DrOn is to represent inducing, inhibiting, and 
"getting metabolized, ie destroyed, by" CYP2C19.  

Although the list will need to be scientifically curated, see 
http://en.wikipedia.org/wiki/CYP2C19 for a starting point.

```

Original issue reported on code.google.com by `hoga...@gmail.com` on 4 Mar 2013 at 9:42

_Copied from original issue: joshhanna/dr-on#6_

**Comment by joshhanna** [comment]
Is this still relevant, or should this issue be closed?

**Comment by mbrochhausen** [comment]
Was this an issue that came up as part of the PDDI project?
It certainly looks like one.

Best,
Mathias

**Comment by joshhanna** [comment]
I have no idea.  If so, is it still relevant to the work?

**Comment by hoganwr** [comment]
It is still relevant.  Right now we just have the disposition on one
compound.  Needs to go on others.

**Comment by hoganwr** [comment]
I am closing this issue as we've added as many CYP2C19 inhibitors and substrates to DrOn as we know about.  Modeling inducers is more complicated because induction is a gene-level thing and not a mere enzyme-binding thing.
