### ISSUE TITLE
Build pipeline to automatically swap in CHEBI ids for DRON ids

### ISSUE THREAD

**Issue by matentzn** [ufbmi/dron#4]
Needs to:
- [x] Update edit files as one-offs (ID swapping is a curation step and does not happen automatically on dron-edit.owl)
- [x] Add goal to update edit files
- [x] Add ROBOT rename pipeline dynamically to components (happens every time Dron is updated automatically)
- [ ] Document updated pipeline

**Comment by matentzn** [comment]
Fixed in https://github.com/ufbmi/dron/pull/5

**Comment by sjbost** [comment]
@hoganwr will review documentation, determine where to add content on updated CHEBI replacement pipeline.

**Comment by sjbost** [comment]
@hoganwr aims to add this documentation by 12.15.22
